server:
  port: 8767
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springcloudlearning/SpringcloudConfig
          search-paths:
          - respo
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/